services:
  - type: web
    name: mrfrank-obfuscator
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
